[package]
name = "petrinet"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
serde = ""
serde_json = ""
serde_derive = ""
fancy-regex = "0.4.1"

[[bin]]
name = "convert-to-process-io"
path = "src/parse_regex.rs"